name = "homa-ai-core"
main = "homa-ai-worker.js"
compatibility_date = "2024-09-01"

[[kv_namespaces]]
binding = "GOOGLE_TOKENS"
id = "cf4d81add5a44f42a32cff34c46e2f90"

[[kv_namespaces]]
binding = "USER_CONNECTIONS"
id = "f5ccb2cffddf4e14ac9fd2346d81ba7e"

[[d1_databases]]
binding = "DB"
database_name = "homa-ai-db"
database_id = "8b44a446-8a82-4a42-a43b-737c54358228"

[triggers]
crons = ["*/30 * * * *"]
