const STR = {
  fa: {
    tab_editor: 'ویرایشگر',
    tab_templates: 'قالب‌ها',
    tab_saved: 'ذخیره‌شده',
    tab_ai: 'پرامپت هوشمند',
    pe_type: 'نوع',
    pe_image: 'تصویر',
    pe_video: 'ویدئو',
    pe_category: 'دسته‌بندی',
    pe_aspect: 'نسبت تصویر',
    pe_resolution: 'رزولوشن',
    pe_sections: 'بخش‌های پرامپت',
    pe_subject: 'موضوع (Subject)',
    pe_environment: 'محیط (Environment)',
    pe_lighting: 'نورپردازی (Lighting)',
    pe_camera: 'دوربین (Camera)',
    pe_motion: 'حرکت (Motion)',
    pe_style: 'سبک (Style)',
    pe_negative: 'پرامپت منفی (Negative)',
    pe_preview: 'پیش‌نمایش پرامپت',
    pe_empty: 'هنوز چیزی ننوشته‌اید...',
    pe_copy: 'کپی',
    pe_copied: 'کپی شد',
    pe_clear: 'پاک‌کردن',
    pe_cleared: 'فرم پاک شد',
    pe_save: 'ذخیره',
    pe_saved_ok: 'پرامپت ذخیره شد',
    pe_export: 'خروجی متن',
    pe_import: 'ورودی متن',
    pe_import_ok: 'متن وارد شد',
    pe_import_err: 'فایل نامعتبر است',
    pe_no_saved: 'هنوز پرامپتی ذخیره نشده',
    pe_load: 'بارگذاری',
    pe_delete: 'حذف',
    cat_cinematic: 'سینمایی',
    cat_realistic: 'واقع‌گرایانه',
    cat_advertising: 'تبلیغاتی',
    cat_fantasy: 'فانتزی',
    cat_anime: 'انیمه',
    cat_nature: 'طبیعت',
    cat_product: 'محصول',
    pe_ai_desc: 'هر چیزی را توضیح بده تا یک پرامپت حرفه‌ای برایت بسازد',
    pe_ai_placeholder: 'مثلاً: یک تصویر از یک گربه روی پنجره در روز بارانی...',
    pe_ai_text_placeholder: 'مثلاً: برای اینستاگرام یک متن تبلیغاتی برای هُما بنویس...',
    pe_ai_generate: 'تولید پرامپت',
    pe_ai_generating: 'در حال ساخت پرامپت...',
    pe_ai_use: 'پرامپت ساخته شد',
    pe_ai_error: 'ساخت پرامپت ناموفق بود. دوباره تلاش کن.',
    pe_text: 'متن',
    pe_regenerate: 'تولید مجدد'
  },
  ku: {
    tab_editor: 'دەستکاریکەر',
    tab_templates: 'قاڵبەکان',
    tab_saved: 'پاشەکەوتکراو',
    tab_ai: 'پرۆمپتی زیرەک',
    pe_type: 'جۆر',
    pe_image: 'وێنە',
    pe_video: 'ڤیدیۆ',
    pe_category: 'پۆلێنکردن',
    pe_aspect: 'ڕێژەی وێنە',
    pe_resolution: 'ڕیزۆلیوشن',
    pe_sections: 'بەشەکانی پرۆمپت',
    pe_subject: 'بابەت (Subject)',
    pe_environment: 'ژینگە (Environment)',
    pe_lighting: 'ڕووناکی (Lighting)',
    pe_camera: 'کامێرا (Camera)',
    pe_motion: 'جووڵە (Motion)',
    pe_style: 'شێواز (Style)',
    pe_negative: 'پرۆمپتی نەرێنی (Negative)',
    pe_preview: 'پیشاندانی پرۆمپت',
    pe_empty: 'هێشتا هیچت نەنووسیوە...',
    pe_copy: 'کۆپی',
    pe_copied: 'کۆپی کرا',
    pe_clear: 'سڕینەوە',
    pe_cleared: 'فۆرم سڕایەوە',
    pe_save: 'پاشەکەوت',
    pe_saved_ok: 'پرۆمپت پاشەکەوت کرا',
    pe_export: 'دەرکردنی دەق',
    pe_import: 'هێنانەژوور',
    pe_import_ok: 'دەق هاتەژوور',
    pe_import_err: 'فایلەکە نادروستە',
    pe_no_saved: 'هێشتا پرۆمپت پاشەکەوت نەکراوە',
    pe_load: 'بارکردن',
    pe_delete: 'سڕینەوە',
    cat_cinematic: 'سینەمایی',
    cat_realistic: 'واقعی',
    cat_advertising: 'ڕیکلام',
    cat_fantasy: 'خەیاڵی',
    cat_anime: 'ئەنیمێ',
    cat_nature: 'سروشت',
    cat_product: 'بەرهەم',
    pe_ai_desc: 'هەر شتێک ڕوون بکەرەوە بۆ دروستکردنی پرۆمپتی پیشەیی',
    pe_ai_placeholder: 'بۆ نموونە: وێنەیەکی پشیلە لەسەر پەنجەرە لە ڕۆژێکی باراناوی...',
    pe_ai_text_placeholder: 'بۆ نموونە: بۆ ئینستاگرام دەقێکی ڕیکلام بۆ هۆما بنووسە...',
    pe_ai_generate: 'دروستکردنی پرۆمپت',
    pe_ai_generating: 'لە دروستکردنی پرۆمپت...',
    pe_ai_use: 'پرۆمپت دروست کرا',
    pe_ai_error: 'دروستکردنی پرۆمپت سەرکەوتوو نەبوو. دووبارە هەوڵبدە.',
    pe_text: 'دەق',
    pe_regenerate: 'دروستکردنی نوێ'
  },
  en: {
    tab_editor: 'Editor',
    tab_templates: 'Templates',
    tab_saved: 'Saved',
    tab_ai: 'AI Prompt',
    pe_type: 'Type',
    pe_image: 'Image',
    pe_video: 'Video',
    pe_category: 'Category',
    pe_aspect: 'Aspect Ratio',
    pe_resolution: 'Resolution',
    pe_sections: 'Prompt Sections',
    pe_subject: 'Subject',
    pe_environment: 'Environment',
    pe_lighting: 'Lighting',
    pe_camera: 'Camera',
    pe_motion: 'Motion',
    pe_style: 'Style',
    pe_negative: 'Negative Prompt',
    pe_preview: 'Prompt Preview',
    pe_empty: 'Nothing written yet...',
    pe_copy: 'Copy',
    pe_copied: 'Copied',
    pe_clear: 'Clear',
    pe_cleared: 'Form cleared',
    pe_save: 'Save',
    pe_saved_ok: 'Prompt saved',
    pe_export: 'Export Text',
    pe_import: 'Import Text',
    pe_import_ok: 'Text imported',
    pe_import_err: 'Invalid file',
    pe_no_saved: 'No saved prompts yet',
    pe_load: 'Load',
    pe_delete: 'Delete',
    cat_cinematic: 'Cinematic',
    cat_realistic: 'Realistic',
    cat_advertising: 'Advertising',
    cat_fantasy: 'Fantasy',
    cat_anime: 'Anime',
    cat_nature: 'Nature',
    cat_product: 'Product',
    pe_ai_desc: 'Describe anything and get a professional prompt',
    pe_ai_placeholder: 'e.g. an image of a cat on a windowsill on a rainy day...',
    pe_ai_text_placeholder: 'e.g. Write an Instagram ad for Homa AI...',
    pe_ai_generate: 'Generate Prompt',
    pe_ai_generating: 'Generating prompt...',
    pe_ai_use: 'Prompt generated',
    pe_ai_error: 'Failed to generate prompt. Try again.',
    pe_text: 'Text',
    pe_regenerate: 'Regenerate'
  }
};

export function pe(lang, key) {
  return (STR[lang] || STR.fa)[key] || STR.fa[key] || key;
}